HW6done
filianov/NodeHW pull request #7
Opened 2020-08-08 09:57 UTC by filianov

2020-08-08 16:09 UTC, odykyi commented on users/users.controller.js
> +    const verificationLink = `http://localhost:3068/auth/verify/${verificationToken}`;
use process env port

2020-08-08 16:09 UTC, odykyi requested changes
comments

2020-08-09 04:02 UTC, filianov commented on users/users.controller.js
> +    const verificationLink = `http://localhost:3068/auth/verify/${verificationToken}`;
Исправил

2020-08-10 09:48 UTC, odykyi approved these changes

2020-08-10 09:48 UTC, merged